In [4]:
import pandas as pd
from pathlib import Path
from IPython.display import display

# Répertoire des CSV (ajuster si nécessaire)
data_dir = Path("../data/raw")

# Lister les CSV
csv_paths = sorted(data_dir.glob("*.csv")) if data_dir.exists() else []

if not csv_paths:
    print(f"Aucun CSV trouvé dans {data_dir}. Vérifiez le chemin.")
else:
    print(f"{len(csv_paths)} fichiers CSV trouvés : {[p.name for p in csv_paths]}")

# Fonction de chargement robuste
def load_csv_with_fallback(path, encodings=('utf-8', 'cp1252', 'latin-1')):
    for enc in encodings:
        try:
            return pd.read_csv(path, encoding=enc, engine='python')
        except UnicodeDecodeError:
            continue
        except Exception as e:
            # Si erreur autre que encodage, on la remonte pour diagnostic
            raise
    # Si tous les encodages échouent, ouvrir en remplaçant les octets invalides
    with open(path, 'r', encoding='utf-8', errors='replace') as fh:
        return pd.read_csv(fh, engine='python')

# Charger tous les CSV dans un dict
dataframes = {}
for p in csv_paths:
    try:
        dataframes[p.name] = load_csv_with_fallback(p)
    except Exception as e:
        print(f"Erreur en chargeant {p.name}: {e}")
        dataframes[p.name] = None

# Résumé rapide
for name, df in dataframes.items():
    if df is None:
        print(f"{name}: échec du chargement.")
    else:
        print(f"{name}: {df.shape}")
        display(df.head())

5 fichiers CSV trouvés : ['data_de_aus_ch.csv', 'ski-resorts.csv', 'ski_resorts_2022.csv', 'ski_resorts_2024.csv', 'snow_coverage.csv']
data_de_aus_ch.csv: (240928, 14)

,Region,Country,Year,Month,Day,Elevation (m),Wind (Beaufort),Temperature (°C),Precipitation (mm),Daily Snow Depth (cm),Monthly Snow Depth (cm),Mean Snow Depth (cm),Max Snow Depth (cm),Days where AVG Temp < 0C
0,Adelboden,Switzerland,2000,1,NaN,NaN,NaN,NaN,NaN,NaN,71.0,49.580645,86.0,31.0
1,Adelboden,Switzerland,2000,2,NaN,NaN,NaN,NaN,NaN,NaN,93.0,40.137931,69.0,29.0
2,Adelboden,Switzerland,2000,3,NaN,NaN,NaN,NaN,NaN,NaN,63.0,19.129032,56.0,28.0
3,Adelboden,Switzerland,2000,4,NaN,NaN,NaN,NaN,NaN,NaN,10.0,0.366667,4.0,5.0
4,Adelboden,Switzerland,2000,5,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,0.0,0.0

ski-resorts.csv: (3284, 14)

,rank,name,rating,url,location_coordinate,location_country,location_region,elevation_top_m,elevation_difference_m,total_slope_length_km,number_of_lifts,number_of_slopes,annual_snowfall_cm,number_of_matches
0,1,4 Vallées (Verbier),1311.7,http://www.4vallees.ch,"{'lat': '46.1013', 'long': '7.2263'}",Switzerland,Valais,3330.0,1980.0,412.0,68.0,307.0,500.0,65
1,2,Matterhorn (Zermatt/Cervinia),1296.8,https://www.matterhornparadise.ch/,"{'lat': '45.9845', 'long': '7.7481'}",Switzerland,Valais,3899.0,2337.0,322.0,51.0,69.0,450.0,49
2,3,Les 3 Vallées (Val Thorens/Méribel/Courchevel),1233.0,https://www.les3vallees.com/,"{'lat': '45.295', 'long': '6.580'}",France,Savoie,3230.0,2130.0,600.0,156.0,61.0,500.0,9
3,4,Chamonix Mont-Blanc,1214.2,https://www.chamonix.com,"{'lat': '45.9237', 'long': '6.8694'}",France,Auvergne-Rhône-Alpes,3842.0,2807.0,152.0,65.0,102.0,450.0,21
4,5,Zell am See-Kaprun,1181.7,https://www.zellamsee-kaprun.com/,"{'lat': '47.3231', 'long': '12.7768'}",Austria,Schwaz,3029.0,2261.0,138.0,49.0,26.0,600.0,25

ski_resorts_2022.csv: (499, 25)

,ID,Resort,Latitude,Longitude,Country,Continent,Price,Season,Highest point,Lowest point,...,Snow cannons,Surface lifts,Chair lifts,Gondola lifts,Total lifts,Lift capacity,Child friendly,Snowparks,Nightskiing,Summer skiing
0,1,Hemsedal,60.928244,8.383487,Norway,Europe,46,November - May,1450,620,...,325,15,6,0,21,22921,Yes,Yes,Yes,No
1,2,Geilosiden Geilo,60.534526,8.206372,Norway,Europe,44,November - April,1178,800,...,100,18,6,0,24,14225,Yes,Yes,Yes,No
2,3,Golm,47.057810,9.828167,Austria,Europe,48,December - April,2110,650,...,123,4,4,3,11,16240,Yes,No,No,No
3,4,Red Mountain Resort-Rossland,49.105520,-117.846280,Canada,North America,60,December - April,2075,1185,...,0,2,5,1,8,9200,Yes,Yes,Yes,No
4,5,Hafjell,61.230369,10.529014,Norway,Europe,45,November - April,1030,195,...,150,14,3,1,18,21060,Yes,Yes,Yes,No

ski_resorts_2024.csv: (499, 25)

,ID,Resort,Latitude,Longitude,Country,Continent,Price,Season,Highest point,Lowest point,...,Snow cannons,Surface lifts,Chair lifts,Gondola lifts,Total lifts,Lift capacity,Child friendly,Snowparks,Nightskiing,Summer skiing
0,1,Hemsedal,60.928244,8.383487,Norway,Europe,46,November - May,1450,620,...,325,15,6,0,21,22921,Yes,Yes,Yes,No
1,2,Geilosiden Geilo,60.534526,8.206372,Norway,Europe,44,November - April,1178,800,...,100,18,6,0,24,14225,Yes,Yes,Yes,No
2,3,Golm,47.057810,9.828167,Austria,Europe,48,December - April,2110,650,...,123,4,4,3,11,16240,Yes,No,No,No
3,4,Red Mountain Resort-Rossland,49.105520,-117.846280,Canada,North America,60,December - April,2075,1185,...,0,2,5,1,8,9200,Yes,Yes,Yes,No
4,5,Hafjell,61.230369,10.529014,Norway,Europe,45,November - April,1030,195,...,150,14,3,1,18,21060,Yes,Yes,Yes,No

snow_coverage.csv: (5488, 1)

  numer_sta;date;haut_sta;dd;ff;t;td;u;ww;w1;w2;n;nbas;hbas;cl;cm;ch;rr24;tn12;tn24;tx12;tx24;ht_neige;ssfrai;perssfrai;phenspe1;phenspe2;nnuage1;t_neige;etat_neige;prof_sonde;nuage_val;chasse_neige;aval_descr;aval_genre;aval_depart;aval_expo;aval_risque;dd_alti;ff_alti;ht_neige_alti;neige_fraiche;teneur_eau;grain_predom;grain_nombre;grain_diametr;homogeneite;m_vol_neige;;
0  07726;20000101070000;1380.000000;0;0.000000;mq...
1  07456;20000101080000;2180.000000;0;0.000000;26...
2  07457;20000101080000;790.000000;0;0.000000;269...
3  07458;20000101080000;1160.000000;mq;mq;mq;mq;m...
4  07484;20000101080000;1020.000000;0;0.000000;27...